# Loki configuration
# Log aggregation and storage

loki:
  fullnameOverride: loki
  
  loki:
    commonConfig:
      replication_factor: 1
    limits_config:
      ingestion_rate_mb: 64
      ingestion_burst_size_mb: 128
      per_stream_rate_limit: 64MB
      per_stream_rate_limit_burst: 128MB
      max_streams_per_user: 50000
      max_global_streams_per_user: 100000
    storage:
      type: 'filesystem'
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    schemaConfig:
      configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
    ingester:
      chunk_encoding: snappy
    tracing:
      enabled: true
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4
  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
    extraEnv:
      # Keep a little bit lower than memory limits
      - name: GOMEMLIMIT
        value: 1800MiB
  chunksCache:
    # default is 500MB, with limited memory keep this smaller
    writebackSizeLimit: 10MB
    allocatedMemory: 512
  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations: {}
    labels: {}
    paths:
      distributor:
        - /ready
        - /api/prom/push
        - /loki/api/v1/push
        - /otlp/v1/logs
      queryFrontend:
        - /api/prom/query
        # this path covers labels and labelValues endpoints
        - /api/prom/label
        - /api/prom/series
        - /api/prom/tail
        - /loki/api/v1/query
        - /loki/api/v1/query_range
        - /loki/api/v1/tail
        # this path covers labels and labelValues endpoints
        - /loki/api/v1/label
        - /loki/api/v1/labels
        - /loki/api/v1/series
        - /loki/api/v1/index/stats
        - /loki/api/v1/index/volume
        - /loki/api/v1/index/volume_range
        - /loki/api/v1/format_query
        - /loki/api/v1/detected_field
        - /loki/api/v1/detected_fields
        - /loki/api/v1/detected_labels
        - /loki/api/v1/patterns
      ruler:
        - /api/prom/rules
        - /api/prom/api/v1/rules
        - /api/prom/api/v1/alerts
        - /loki/api/v1/rules
        - /prometheus/api/v1/rules
        - /prometheus/api/v1/alerts
    # -- Hosts configuration for the ingress, passed through the `tpl` function to allow templating
    hosts:
      - loki.k8s.test
  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0
