# helm/umbrella-chart/Chart.yaml
apiVersion: v2
name: observability-stack
version: 0.1.0
dependencies:
  - name: loki
    version: "6.36.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: tempo
    version: "1.23.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled
  #- name: tempo2
  #  version: "1.23.3"
  #  repository: "https://grafana.github.io/helm-charts"
  #  condition: tempo2.enabled
    
  - name: prometheus
    version: "27.46.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    alias: grafana-destination
    version: "10.2.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana-destination.enabled

  - name: grafana
    version: "10.2.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  # Using local chart from NGDATA fork with monolithic support
  - name: mimir-distributed
    version: "5.9.0-weekly.365"
    repository: "file://./charts/mimir-distributed"
    condition: mimir.enabled
    alias: mimir

  - name: minio
    version: "17.0.21"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
  - name: opentelemetry-collector
    version: "0.122.2"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-collector.enabled